fix nft viewer background issues
schnoodledefi/contracts pull request #4
Opened 2022-04-11 09:48 UTC by koteakhaladze

2022-04-11 10:24 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/viewer/viewer.js
> +        //.setDataType( UnsignedByteType )
Just remove instead of commenting out.

2022-04-11 10:25 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/viewer/viewer.js
> +      }
Remove trailing whitespace.

2022-04-11 10:25 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/viewer/viewer.js
> +
Carriage return not necessary.

2022-04-11 10:28 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/viewer/viewer.js
> +import FOOTPRINT_COURT from './environments/footprint_court_2k.hdr';
I don't think it's a good idea to hardcode HDR files into the viewer. It will stop us adding more later, and supporting multiple backgrounds will be a feature of the viewer.

2022-04-11 10:29 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/viewer/viewer.js
> +    const background = (id == 'venice-sunset') ? VENICE_SUNSET : FOOTPRINT_COURT;
See comment [above](https://github.com/schnoodledefi/contracts/pull/4/files#r847177561).

2022-04-11 10:32 UTC, NeoXtreem reviewed
So, how does the [reference project](https://github.com/donmccurdy/three-gltf-viewer) do this with the .vert and .frag files directly instead of compiling to .js files?

2022-04-19 02:11 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/craco.config.js
> +    },
Use consistent indenting.

2022-04-19 02:11 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/package.json
> +        "glslify-loader": "^2.0.0",
Are these still required?

2022-04-19 02:13 UTC, NeoXtreem requested changes
PR looks good now. Just a couple of minor tweaks.

2022-04-19 02:13 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/package.json
> +        "raw-loader": "^4.0.2",
Is this still required?

2022-04-19 10:14 UTC, koteakhaladze commented on SchnoodleDApp/ClientApp/package.json
> +        "raw-loader": "^4.0.2",
Yes, here: 
https://github.com/schnoodledefi/contracts/blob/schnoodle-nft-kote/SchnoodleDApp/ClientApp/craco.config.js

2022-04-19 10:14 UTC, koteakhaladze commented on SchnoodleDApp/ClientApp/package.json
> +        "glslify-loader": "^2.0.0",
Yes, here: 
https://github.com/schnoodledefi/contracts/blob/schnoodle-nft-kote/SchnoodleDApp/ClientApp/craco.config.js

2022-04-19 10:14 UTC, koteakhaladze commented on SchnoodleDApp/ClientApp/craco.config.js
> +    },
accepted.

2022-04-19 10:17 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/craco.config.js
> +          use: ['raw-loader', 'glslify-loader']
Oops, you missed a bit. Sorry! 😊

2022-04-19 12:18 UTC, NeoXtreem requested changes

2022-04-19 12:18 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/viewer/viewer.js
> +﻿// ReSharper disable IdentifierTypo
The file was saved as UTF-8 with BOM. Please revert back to UTF-8 without BOM per the [Unicode Standard](http://www.unicode.org/versions/Unicode5.0.0/ch02.pdf) recommendation (page 36).

2022-04-19 12:18 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/viewer/lib/three-vignette.js
> +﻿/**
The file was saved as UTF-8 with BOM. Please revert back to UTF-8 without BOM per the [Unicode Standard](http://www.unicode.org/versions/Unicode5.0.0/ch02.pdf) recommendation (page 36).

2022-04-19 12:18 UTC, NeoXtreem commented on SchnoodleDApp/ClientApp/src/viewer/environments/index.js
> +﻿export const environments = [
The file was saved as UTF-8 with BOM. Please revert back to UTF-8 without BOM per the [Unicode Standard](http://www.unicode.org/versions/Unicode5.0.0/ch02.pdf) recommendation (page 36).

2022-04-19 12:59 UTC, merged